CREATE DATABASE VETERINARIA;
USE VETERINARIA;

#crear las tablas mascotas, personas y direcciones
CREATE TABLE MASCOTAS(
	ID INT NOT NULL,	
    NOMBRE VARCHAR(10),
    ID_DUEÑO INT NOT NULL,
    SERVICIO VARCHAR(10)
);
CREATE TABLE PERSONAS(
	ID INT NOT NULL,
    NOMBRE VARCHAR(10),
    APELLIDO VARCHAR(12),
    COD_ZIP INT NOT NULL,
    TLF INT
);
CREATE TABLE DIRECCIONES(
	ZIP INT NOT NULL,
    NOMBRE_ZONA VARCHAR(10),
    RUTA VARCHAR(40)
);

DESC MASCOTAS;
DESC PERSONAS;
DESC DIRECCIONES;

#AGREGAR PRIMARY KEY EN MASCOTAS
ALTER TABLE MASCOTAS 
ADD PRIMARY KEY (ID);

#AGREGAR PRIMARY KEY EN PERSONAS
ALTER TABLE PERSONAS 
ADD PRIMARY KEY (ID);

#AGREGAR FK AL CAMPO ID_DUEÑO EN MASCOTAS -> ID DE PERSONAS 
ALTER TABLE MASCOTAS
ADD CONSTRAINT FK_PERSONASID
FOREIGN KEY (ID_DUEÑO) REFERENCES PERSONAS(ID);

#AGREGAR FK AL CAMPO COD_ZIP EN PERSONAS -> ZIP DE DIRECCIONES 
ALTER TABLE PERSONAS
ADD CONSTRAINT FK_DIRECCIONESZIP
FOREIGN KEY (COD_ZIP) REFERENCES DIRECCIONES(ZIP);

#AGREGAR UNA COLUMNA EMAIL EN LA TABLA PERSONAS
ALTER TABLE PERSONAS
ADD COLUMN EMAIL VARCHAR (30);

#AGREGAR LA RESTRICCION UNICA EN EMAIL PERSONAS
ALTER TABLE PERSONAS
ADD CONSTRAINT EMAILRES UNIQUE (EMAIL);
  
#CAMBIAR EL NOMBRE DE LA VARIABLE NOMBRE -> PRIMER_NOMBRE
ALTER TABLE PERSONAS CHANGE NOMBRE PRIMER_NOMBRE VARCHAR(10);
#RENAME COLUMN NOMBRE TO PRIMER_NOMBRE

#CAMBIAR EL TIPO DE DATA DE RUTA EN DIRECCIONES
ALTER TABLE DIRECCIONES MODIFY RUTA CHAR(12);
